### ISSUE TITLE
Move Parameter Class to own file 

### ISSUE THREAD

**Issue by JoshuaSBrown** [MikeHeiber/Excimontec#29]
The OSC_Sim files are a little bloated. Readability can be increased by better modular design moving the Parameters class into its own file would be one to do this. It would also be beneficial to get rid of all the members of the OSC_Sim class that refere to the parameters and just make a Parameter Object a member of the OSC_Sim class this would vastly reduce duplication.

**Comment by MikeHeiber** [comment]
These ideas also connect with #14.  I think there probably could be a Parameters class that stores all of the different parameter structs, handles loading in different types and versions of the parameter files, and also checks the validity of the input parameters. This would clean up main and OSC_Sim a good amount.

**Comment by JoshuaSBrown** [comment]
Why do you redefine all the parameters in the OSC_Sim class? Why not have a Parameters_OSC  object as an attribute of the class and simply set the parameter struct equal to it?

**Comment by JoshuaSBrown** [comment]
If in your Lattice Simulation.h class you had a Parameters_Simulation class as attribute this would make it even easier because all those properties would be inherited.

**Comment by MikeHeiber** [comment]
When we build out the Parameters class, we can think about whether it would be better to have the Simulation and OSC_Sim classes have parameters objects as members or not.  I would potentially make things easier, but we'll have to see how it would all fit together.  Because we would again need a base Parameters class in KMC_Lattice and then a derived OSC_Parameters class in Excimontec.

**Comment by MikeHeiber** [comment]
Resolved in #63
